language: csharp
mono:
- latest
cache:
  directories:
  - "$HOME/.taiwu"
install:
- sudo apt-get install -y zip curl cmake
script: pwd && ls && sh .travis/build-linux.bash
deploy:
  provider: releases
  api_key:
    secure: HzoOAoULjaNoNzWF64hkTXu+h5bKu4JK8MIctJ1aQ4FIJWyk+ztRhW65Ja8/5J9CsbmhtEIxjLwCBEM+WWPZNXSF54EkvyRN1F2DqxckPOFXel4eDy6ewQXUkpSMPXElyCwx1MWZ7ovjV8V4CvLj5VHuyxSx0wXyoR+pAiZZEr78qydxTdzDrX/Cqh8krVwEf07DkydsXPF3x6PU0ISUuNVtmsy3YNQSJEHGvQ7QfutCO7M3m44aN36fQQWonhSXz614EfXJJhOZKvPUFLmzxR191ohjkgc2QlfBjKl2eTpXYH+4f29NJG25YhUlaMo2wZWKqDB2R9+AA+eZymkYjOI2GvI+IsxMv4wqu8QnFXYnOdwouD9Jw+Hv19jOP4SaoRp9N4ArFKLnVLF/wJ+Jmwfw0sZMhXIbmc0Xzbd9eW3Sk/OH+K3yrwKJVNX2BVv1VFlZQkTGjKInADZPW2FIOKu/CZKg5U90AiP5B2afrgdNd/aLF6RzgudLXnAdkL+LXvkKoCDCSSJThyMaS2+vL6gzKRlwFnbfnHsawHzoDPhw+u57u7GHzYjxF/qfzu1uUXvDwM/L/6ekm8+oFjpwe8ZWzDT5n+17ZjIOhOSPeWkxFeElhGj4O1pvNh2CN3zUolllUAN5z6ujd2RbXoiD3/415g1aUYvYtWpYPExAK1w=
  file_glob: true
  file: build/Mods_Publish/*
  skip_cleanup: true
  on:
    repo: phorcys/Taiwu_mods
    tags: true
